### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by faisalhr1997** [mcmonkeyprojects/sd-dynamic-thresholding#1]
![image](https://user-images.githubusercontent.com/97628039/215087880-300a57d6-93d8-43c6-bd21-a58ca3e336ae.png)

**Comment by mcmonkey4eva** [comment]
`match` syntax was introduced by Python 3.10, which is the support target for the WebUI - it used to target 3.9 though, so I imagine what happened here is your Python install is outdated?

**Comment by faisalhr1997** [comment]
Using it in Google colab

**Comment by mcmonkey4eva** [comment]
Argh, yeah, I forgot colab has outdated python for some reason.
I replaced the `match` syntax with something backwards compatible.
