### ISSUE TITLE
Error after installing / starting UI:  "Cannot import name 'sd_samplers_kdiffusion' from 'modules' (unknown location)"

### ISSUE THREAD

**Issue by CCpt5** [mcmonkeyprojects/sd-dynamic-thresholding#10]
Hello!

I'm trying to test out your extension for the first time. I'm on the latest A1111 commit and installed via the extension tab. When restarting the Webui I get the following error. Any idea how I can resolve this? Sorry if it's a newbie question or due to a modification I made in the past. I appreciate any help and your work. Thx!

BTW: Using a CPU search tool I don't have a file called sd_samplers_kdiffusion, but I do have one in modules called sd_samplers_kdiffusion.cpython-310.pyc (C:\stable-diffusion-webui\modules\__pycache__\sd_samplers_kdiffusion.cpython-310.pyc)

Error:
____
Closing server running on port: 7860
Restarting UI...
Error loading script: dynamic_thresholding.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 16, in <module>
    from modules import scripts, sd_samplers, sd_samplers_kdiffusion, sd_samplers_common
ImportError: cannot import name 'sd_samplers_kdiffusion' from 'modules' (unknown location)

**Comment by mcmonkey4eva** [comment]
Are you sure you're up to date on the WebUI? 
The relevant file was added to the WebUI just 3 weeks ago @ https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_samplers_kdiffusion.py

**Comment by CCpt5** [comment]
My apologies - I'm actually on a commit 3 weeks back due to PNG info's model changing feature (send to TXT2IMG etc) getting broken at that point (Re: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7394).

I forgot I had jumped back to the commit before that broke as I use that feature often.

I'll reinstall the extension after I'm able to go back to the current commit.

Thanks a lot, and sorry for incorrectly indicating I'm up to date.
