### ISSUE TITLE
Power Scheduler Value is not stored in image metadata

### ISSUE THREAD

**Issue by VampirkoOrus** [mcmonkeyprojects/sd-dynamic-thresholding#13]
> Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 30, Seed: 1615917251, Size: 544x800, Model hash: 51710d9efa, Model: 0.7(Si28-negz)+0.3(dreamlike1.0), Denoising strength: 0.65, Hires upscale: 1.5, Hires steps: 24, Hires upscaler: Latent (bicubic antialiased), Dynamic thresholding enabled: True, Mimic scale: 13.5, Threshold percentile: 98.7, Mimic mode: Half Cosine Up, Mimic scale minimum: 6, CFG mode: Half Cosine Up, CFG scale minimum: 9

Power Scheduler Value is not stored in image metadata, so it is not restored when using PNG info tab, instead is set to a default value of 4.

**Comment by mcmonkey4eva** [comment]
it's only stored if you actually, uh, use the Power scheduler, which you aren't there (you're using Half Cosine Up).

**Comment by VampirkoOrus** [comment]
I see, sorry. I was under impression it had an effect, due to it being exposed when the half cosine up was selected, and there being variations upon changing it, but upon further testing i confirmed that variations are there because of xformers.

**Comment by mcmonkey4eva** [comment]
I've updated the UI to hide the Power scheduler value input until you select a Power scheduler, to hopefully avoid this confusion in the future.
