### ISSUE TITLE
Mac M1 Error - min and input tensors must be of the same shape

### ISSUE THREAD

**Issue by bingoYB** [mcmonkeyprojects/sd-dynamic-thresholding#15]
Help！How can I solve the problem

Error img:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/24823972/223100153-701d32d9-785e-4981-985d-5348cd8a2ef3.png">

img Config
![image](https://user-images.githubusercontent.com/24823972/223100518-1b39ebfc-5178-4276-97ca-fc220215c6de.png)

system: MacBook Pro (13-inch, M1, 2020)

**Comment by icedac** [comment]
I fixed it; the problem is the script for macos are outdated.

Replace a line webui-macos-env.sh scripts with proper version

```
export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
```

```
export TORCH_COMMAND="pip install torch==1.13.1 torchvision==0.14.1"
```

And reinstall torch

```
./webui.sh --reinstall-torch
```

**Comment by wifeyole** [comment]
> I fixed it; the problem is not this project but webui; the script for macos are outdated.
> 
> Replace a line webui-macos-env.sh scripts with proper pytorch version
> 
> ```
> export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
> ```
> 
> ```
> export TORCH_COMMAND="pip install torch==1.13.1 torchvision==0.14.1"
> ```
> 
> And reinstall torch
> 
> ```
> ./webui.sh --reinstall-torch
> ```
> 
> note: I asked it to gpt4 and gpt4 tell me it's problem of pytorch.

Hey!

I'm a bit new and ignorant about coding or stable diffusion, but i have the same problem as op, tried to follow what you said changing the ver in the scripts, but the last step.. i can't understand where exactly i should put the command. 

If you dont mind me asking and sorry!

**Comment by shelly-luo** [comment]
> I fixed it; the problem is not this project but webui; the script for macos are outdated.
> 
> Replace a line webui-macos-env.sh scripts with proper pytorch version
> 
> ```
> export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
> ```
> 
> ```
> export TORCH_COMMAND="pip install torch==1.13.1 torchvision==0.14.1"
> ```
> 
> And reinstall torch
> 
> ```
> ./webui.sh --reinstall-torch
> ```
> 
> note: I asked it to gpt4 and gpt4 tell me it's problem of pytorch.

Thank you very much, it works for me!

**Comment by no7bed** [comment]
> I fixed it; the problem is not this project but webui; the script for macos are outdated.
> 
> Replace a line webui-macos-env.sh scripts with proper pytorch version
> 
> ```
> export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
> ```
> 
> ```
> export TORCH_COMMAND="pip install torch==1.13.1 torchvision==0.14.1"
> ```
> 
> And reinstall torch
> 
> ```
> ./webui.sh --reinstall-torch
> ```
> 
> note: I asked it to gpt4 and gpt4 tell me it's problem of pytorch.

**Comment by no7bed** [comment]
> I fixed it; the problem is not this project but webui; the script for macos are outdated.
> 
> Replace a line webui-macos-env.sh scripts with proper pytorch version
> 
> ```
> export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
> ```
> 
> ```
> export TORCH_COMMAND="pip install torch==1.13.1 torchvision==0.14.1"
> ```
> 
> And reinstall torch
> 
> ```
> ./webui.sh --reinstall-torch
> ```
> 
> note: I asked it to gpt4 and gpt4 tell me it's problem of pytorch.

Thank you very much, it works for me too!

my webui-macos-env.sh is
export TORCH_COMMAND="pip install torch==2.0.1 torchvision==0.15.2"

so, I just do   ./webui.sh --reinstall-torch
than, it works
