### ISSUE TITLE
Failed to add XYZ plot support

### ISSUE THREAD

**Issue by wwwWolfcom** [mcmonkeyprojects/sd-dynamic-thresholding#16]
Failed to add support for X/Y/Z Plot Script because: list index out of range

using colab, python 3.8

I inspected .py but couldnt find reason since  I dont know how add xyz plot works.

**Comment by mcmonkey4eva** [comment]
Please first make sure you're fully up to date on both the WebUI itself, and the extension.
Then, post the full error message as it appears in your console.

**Comment by wwwWolfcom** [comment]
> Please first make sure you're fully up to date on both the WebUI itself, and the extension. Then, post the full error message as it appears in the colab's console logger.

Its fully up to date. Web ui - latest repo
DT - up to date

The error appears but i can run web ui normaly, Just xyz plot does not support DT variables.

![Screenshot_20230313_181659_QuickEdit](https://user-images.githubusercontent.com/60924830/224658328-c55ec100-03ab-442b-b551-3d4f966bfe63.jpg)

**Comment by mcmonkey4eva** [comment]
I added better error outputs to make that clearer if you replicate it again.

However the only reason I can see that error happening is if `xyz_grid` does not exist, which would occur only if either (A) you've deleted files in the the webui's code, or (B) you have an outdated copy of the webui.

You appear to have a recent-enough Commit hash, so outdated shouldn't be an issue.

I tried loaded the WebUI in a colab - https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb - and added DynThres and it was able to load without any issue, it's in XYZ Plot and all.

So... only thing I can think of is that for some reason the files in your webui `scripts` folder were modified such that `xyz_grid` does not exist (ie either deleted or renamed).

**Comment by wwwWolfcom** [comment]
Traceback (most recent call last):
	  File "/content/drive/MyDrive/SD/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py", line 280, in <module>
	    make_axis_options()
	  File "/content/drive/MyDrive/SD/extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py", line 257, in make_axis_options
	    xyz_grid = [x for x in scripts.scripts_data if x.script_class.__module__ == "xyz_grid.py"][0].module
	IndexError: list index out of range
	Failed to add support for X/Y/Z Plot Script because: list index out of range


xyz grid.py is exist in scripts folder.

**Comment by mcmonkey4eva** [comment]
Are you sure that
A: it actually exists
B: it's named `xyz_grid.py` exactly (not eg a space instead of the underscore as you wrote)
C: it's actually loading, without any error?

**Comment by mcmonkey4eva** [comment]
Had a new theory about why it might go wrong actually - maybe there's a load order issue? I pushed a new commit that will solve it if that's the case.

**Comment by wwwWolfcom** [comment]
So sorry for bothering you.
New commit solved the problem. Really appreciate!
