### ISSUE TITLE
Missing sd_samplers

### ISSUE THREAD

**Issue by Soulreaver90** [mcmonkeyprojects/sd-dynamic-thresholding#18]
Do I need to be on the latest Auto1111 commit? I installed the extension and it fails to load with the following:
 "from modules import scripts, script_callbacks, sd_samplers, sd_samplers_kdiffusion, sd_samplers_common
ImportError: cannot import name 'sd_samplers_kdiffusion' from 'modules' (unknown location)"

I checked the folder and don't see sd_samplers_kdiffusion or sd_samplers_common.

EDIT: I checked and my commit is from earlier January, before the original sd_samplers were split. Is it needed? Could the code be updated to simply import sd_samplers if kdfiffusion/common are not located? I don't want to upgrade as I am getting faster speeds and stability with this old commit but I do want to try this extension.

**Comment by mcmonkey4eva** [comment]
Yes you need to update the WebUI, or downdate the extension to match your WebUI version.
