### ISSUE TITLE
The generated image has extremely low contrast

### ISSUE THREAD

**Issue by oldboss918** [mcmonkeyprojects/sd-dynamic-thresholding#30]
The generated image has extremely low contrast, as if there were no VAE involved, and the image tends to be burned out at low resolutions. This problem occurs with various sampling methods. The plugin and CFG settings are as follows: 

(CFG Scale)
24

Mimic CFG Scale
9

Dynamic Thresholding Advanced Options
▼
Top percentile of latents to clamp
100

Mimic Scale Scheduler
Constant
Minimum value of the Mimic Scale Scheduler
0

CFG Scale Scheduler
Half Cosine Up
Minimum value of the CFG Scale Scheduler
4

**Comment by vt-idiot** [comment]
That's entirely because of your settings.

>Top percentile of latents to clamp
>100
>Mimic Scale Scheduler
>Constant
>0

Set clamp percentile to 95, set the mimic scale scheduler to half cosine up, 4. Bam, bet you it's not washed out anymore.

**Comment by mcmonkey4eva** [comment]
Yep, better settings like that should help a lot.

Do note that the core function of dynamic thresholding is to fix _hyper contrast_ and/or hypersaturation that occurs when cranking CFG scale up normally, so over-aggressive settings can end up going the opposite direction and underdoing the contrast.
