### ISSUE TITLE
Send to img2img/inpaint

### ISSUE THREAD

**Issue by matrix4767** [mcmonkeyprojects/sd-dynamic-thresholding#31]
If an output that used this extension was sent to img2img/inpaint, could it stay enabled? Currently it doesn't.

**Comment by mcmonkey4eva** [comment]
I'm a bit confused, the txt2img page's "send to img2img" seems to just ignore most parameters regardless, even normal CFG Scale doesn't send over. The Png Info tab does send everything over as expected though.
Might be an upstream WebUI bug here?
