### ISSUE TITLE
Optimized defaults

### ISSUE THREAD

**Issue by baaoh** [mcmonkeyprojects/sd-dynamic-thresholding#32]
Hi, amazing extension, love using it, and it provides amazing results.

My issue is that the default values in the advanced tab dont yield good results, and I always have to change them to optimized

"Half cosine up" + Minimum scheduler 5

Can this be changed to default to these?

**Comment by mcmonkey4eva** [comment]
You can configure your personal defaults by altering `ui-config.json`

Configuration tips are on the wiki: https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/wiki/Usage-Tips

Different configurations work well for different goals, the default is configured to be the least intrusive out-of-the-box, I've thought about making easy presets but haven't gotten to implementing them yet.
