### ISSUE TITLE
Mimic and cfg scale scheduler settings not saved in image data when they are unchanged.

### ISSUE THREAD

**Issue by matti187** [mcmonkeyprojects/sd-dynamic-thresholding#34]
This causes mimic and cfg scale scheduler settings being left unchanged and results in a different image when you load data from an image with default values after generating an image with different settings. It is a bit annoying.

**Comment by mcmonkey4eva** [comment]
Fixed! It's not added to image data still, but rather it now knows to automatically reset to "Constant" if the values aren't present.
