### ISSUE TITLE
Dynamic thresholding causes sampler returned by `parse_generation_parameters` to be invalid

### ISSUE THREAD

**Issue by evanjs** [mcmonkeyprojects/sd-dynamic-thresholding#37]
When dynamic thresholding is enabled, the sampler returned by "return generation parameters from prompt or last generation" is affixed with `_dynthres<num>`

This appears to happen [here](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/blob/5d3465c4b2d5dacfdd6caa38b71b23b4f88401c0/scripts/dynamic_thresholding.py#L102).

After copypasting the previous generation data, the sampler must be edited manually to remove the suffix, or generation will fail, as e.g. `DPM++ SDE Karras_dynthres1` is not a valid sampler.

**Comment by mcmonkey4eva** [comment]
Replicated and fixed, by manually emitting the original sampler name into the parameter set. Seems to work fine.
