### ISSUE TITLE
Send by sdapi/v1/text2img

### ISSUE THREAD

**Issue by bincooo** [mcmonkeyprojects/sd-dynamic-thresholding#38]
How to pass parameters in this api ' sdapi/v1/text2img'?

**Comment by mcmonkey4eva** [comment]
I don't entirely know, I don't work with the webui API much. Might have to learn how soon.

For now, check this issue: https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/issues/20 probably subscribe to notifications there too.
If I find a better solution myself or somebody posts one at any point, it'll get posted into there.
