### ISSUE TITLE
[Feature Request] Add dynamic thresholding extension settings to image generation data

### ISSUE THREAD

**Issue by nabileisa** [mcmonkeyprojects/sd-dynamic-thresholding#4]
Hello, first thank you for the extension 
As it is now if you were to copy the generation data contained in the image and run it in a different instance that don't have it enabled with the exact same settings of the original , the resulting image would be different
It would be helpful if the images generated while the extension is enabled contained all the settings of the extensions .
thank you.

**Comment by mcmonkey4eva** [comment]
Yep, good point! Added.
