### ISSUE TITLE
Dynamic Thresholding's Influence on Other Extensions' CFG Scale

### ISSUE THREAD

**Issue by CaL9Mi7Y** [mcmonkeyprojects/sd-dynamic-thresholding#43]
Hi. Just a quick question. Does Dynamic Thresholding affect the CFG Scale settings of other Automatic1111 extensions, in any way?

There are many examples of these popular extensions, but off the top of my head, how about ADetailer/After Detailer? And if yes, how so? Does Dynamic Thresholding "add" to their settings, or does it completely override them, or is the effect something else entirely?

Anyway, thanks in advance.

**Comment by mcmonkey4eva** [comment]
That is a per-extension question, depends what the other extension does. DynThresh's alteration exist within a sampler override, so only things that use `p.sampler` will potentially be altered.
