### ISSUE TITLE
Missing some functionality

### ISSUE THREAD

**Issue by TubeStorm** [mcmonkeyprojects/sd-dynamic-thresholding#44]
Hey, I need some guidance.
I recently got this extension and what I see is a bit different from the readme.

- I don't see the advanced options you talked about [here ](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/wiki/Usage-Tips) nor the "top percentile of latents..."

Readme
![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/18316153/a55b3a80-ffcf-4714-b860-b1d213963080)

Mine
![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/18316153/22dc895b-3bc0-4bfa-adf9-31cd9349d335)

**Comment by mcmonkey4eva** [comment]
yeah open the 'advanced options' dropdown
