### ISSUE TITLE
*** Error running process_batch: D:\AI\webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py  

### ISSUE THREAD

**Issue by Monshilstraze** [mcmonkeyprojects/sd-dynamic-thresholding#48]
Error line:
*** Error running postprocess_batch: D:\AI\webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
    Traceback (most recent call last):
      File "D:\AI\webui\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'sched_val'

This is after the new update, 1.4.0 version. Before the update everything was fine. 
I tried deleting the extension and installing it again. Tried downloading a clear webui and running it there, still the same. 
Any ideas?

**Comment by mcmonkey4eva** [comment]
Uh... well that doesn't happen for me? You're the only one reporting this. I'm on v1.4.0.

Have you made sure to reload the webpage after updates? That can cause weird errors sometimes if you don't full-refresh the page.

**Comment by Rkkss** [comment]
can't use it with multidiffusion upscaler

**Comment by mcmonkey4eva** [comment]
If it's a problem that only happens with another extension, it's prooooooobably the other extension that's doing something odd more likely than this one.

**Comment by Monshilstraze** [comment]
Problem went away on its own.

**Comment by mcmonkey4eva** [comment]
lol okay then. If it happens again, let me know, (and if so maybe also toss in links to other reports if you can)

**Comment by Monshilstraze** [comment]
Actually, it happened again in img2img lol. 

Here's the link to other report
[https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11448#issue-1776316105](url)

**Comment by Monshilstraze** [comment]
Okay, after disabling the mov2mov extension the problem seems to be gone. I'll be closing this again, sorry xD

**Comment by Monshilstraze** [comment]
after removing the extension mov2mov the issue seems to be gone. hope it won't come back.
closing.
