### ISSUE TITLE
Desperately need the API docs. please

### ISSUE THREAD

**Issue by PurpleBlueAloeVera** [mcmonkeyprojects/sd-dynamic-thresholding#49]
Hello, love the extension. But I've been losing my mind trying to make it work correctly with API and the advanced settings.. please provide the API docs... PLEASE.

Thanks in advance, hope it can happen.

**Comment by mcmonkey4eva** [comment]
I need to properly test and validate how that works before making an official clear wiki entry for it (I only have a small bit of experience with auto webui api) but https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/issues/20#issuecomment-1560457330 has some info on it

**Comment by PurpleBlueAloeVera** [comment]
> 

`  "alwayson_scripts": {
    "Dynamic Thresholding (CFG Scale Fix)": {
      "args": [
        true, 
        {
          "Mimic CFG Scale":7, 
          "Top percentile of latents to clamp": 100,
          "Mimic Scale Scheduler": "Half Cosine Up",
          "Minimum value of the Mimic Scale Scheduler": 3.5,
          "CFG Scale Scheduler": "Half Cosine Up",
          "Minimum value of the CFG Scale Scheduler": 3.5
          }
         ]
        },`

Here's what I need, I need to control the advanced options from the generate.settings.json.

But I keep getting this error no matter what ID's I type, the HTML ones as much as the correct ones:

`TypeError: Script.postprocess_batch() missing 6 required positional arguments: 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and 'sched_val'`

**Comment by mcmonkey4eva** [comment]
Again, look at the linked post (it doesn't use named args it just uses them positionally)

**Comment by PurpleBlueAloeVera** [comment]
```
  "alwayson_scripts": {
    "Dynamic Thresholding (CFG Scale Fix)": {
      "args": [
        true,
            4,
            100,
            "Half Cosine Up",
            3.5,
            "Half Cosine Up",
            3.5,
	    4.0
            ]
	},
		```
After many failed attempts, this finally ended up working !

**Comment by drphero** [comment]
> ```
>   "alwayson_scripts": {
>     "Dynamic Thresholding (CFG Scale Fix)": {
>       "args": [
>         true,
>             4,
>             100,
>             "Half Cosine Up",
>             3.5,
>             "Half Cosine Up",
>             3.5,
> 	    4.0
>             ]
> 	},
> 		```
> After many failed attempts, this finally ended up working !
> ```

Unfortunately, this doesn't seem to work for me. I don't receive any errors. But the output has a very different style than that of using the same settings within the webui. Also, are you using something other than python? Because true would need to be True.
