### ISSUE TITLE
Not isn't showing up even after restarting

### ISSUE THREAD

**Issue by danganbenpa** [mcmonkeyprojects/sd-dynamic-thresholding#5]
I installed it using webUI's built in extensions tab and it isn't showing up even after restarting.

**Comment by mcmonkey4eva** [comment]
Are you just confused about where it is?
If so:
![](https://cdn.discordapp.com/attachments/355274120566669312/1071406506492317757/image.png)

It's that checkbox there.

if that checkbox isn't there: can you screenshot what your txt2img interface looks like?
Also, are there any errors in your WebUI console window?
