### ISSUE TITLE
make this for diffusers

### ISSUE THREAD

**Issue by alexblattner** [mcmonkeyprojects/sd-dynamic-thresholding#53]
Hi, I would like to use this in diffusers, but I lack the overall understanding of the code. Could you implement this or teach me the code so I could do so myself?

Thanks  in advance :)

**Comment by mcmonkey4eva** [comment]
idk about diffusers.
The impl is all in <https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/blob/master/dynthres_core.py> 
Experiment modes can be ignored.
I tried my best to keep clean variable names and add explanatory `#` comment lines.
Some of the way stuff is handled is weird cursed auto-webui-specific value formatting that I'd struggle to explain as I don't even entirely understand it myself. (particularly the cond shaping at the top to compensate for the way auto webui batches stuff)

**Comment by alexblattner** [comment]
Hey, man. I've tried this and came to the conclusion that it'll be a big pain in the ass. Would you be interested in doing this for cash?

**Comment by alexblattner** [comment]
I made it for diffusers.
