### ISSUE TITLE
ComfyUI

### ISSUE THREAD

**Issue by VolanDeVovan** [mcmonkeyprojects/sd-dynamic-thresholding#54]
is it possible to implement it in ComfyUI?
I tried but I didn't have the skills to do it

**Comment by EricRollei** [comment]
I'm wondering the same thing.  This is the one extension that I used 'everytime' with A1111 that I really miss now that I've switched to ComfyUI

**Comment by mcmonkey4eva** [comment]
Oh have I never replied to this, oops.

I intend to make and release a port to Comfy in the near future. (I just keep getting distracted with other projects)

**Comment by mcmonkey4eva** [comment]
This repo is now _both_ an Auto WebUI extension _and_ a ComfyUI node -- see [the readme](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding#comfyui) for comfy usage info

**Comment by EricRollei** [comment]
Thank you!
