### ISSUE TITLE
please support sdxl

### ISSUE THREAD

**Issue by nishidiaomao** [mcmonkeyprojects/sd-dynamic-thresholding#56]

**Comment by nishidiaomao** [comment]
dynamic_thresholding.py->def combine_denoised(self, x_out, conds_list, uncond, cond_scale):
#add this code
if not isinstance(uncond, torch.Tensor):
  uncond = uncond['crossattn']

**Comment by mcmonkey4eva** [comment]
Fixed, thank you!

The behavior of outputs from dynthresh seems to be fundamentally different on SDXL, so test with care (don't just copy over working settings from SDv1 to SDXL usage).
