### ISSUE TITLE
Issues with radio buttons for scaling_startpoint and variability_measure

### ISSUE THREAD

**Issue by Convexity-ai** [mcmonkeyprojects/sd-dynamic-thresholding#57]
The radio buttons for scaling_startpoint and variability_measure appear blank by default, even if a default is set.

In addition, whenever they're set manually and you hit 'Generate', the radio buttons revert to being blank.

This appears to be visual only and possibly a behavioural issue with with gradio itself. 

Removing the elem_id attribute for these buttons restores functionality, but I'm not sure what impact this has on other parts of the extension.

Edit: The quick workaround I applied, (removed `, elem_id='dynthres_scaling_startpoint'`)
```python
Line 56:    scaling_startpoint = gr.Radio(["ZERO", "MEAN"], value="MEAN", label="Scaling Startpoint")
Line 57:    variability_measure = gr.Radio(["STD", "AD"], value="AD", label="Variability Measure")
```

**Comment by drphero** [comment]
Same problem here.

**Comment by mcmonkey4eva** [comment]
Yeah that's a gradio bug, but i removed the elem ids to workaround the bug for now.

The negative impact is on tacked-on tools like https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/issues/47
