### ISSUE TITLE
SDXL? :)

### ISSUE THREAD

**Issue by oliverban** [mcmonkeyprojects/sd-dynamic-thresholding#62]
Hey!

Will this be updated to work with SDXL in A1111? :) This is such an awesome little gem, but I miss it when working with SDXL. I know the process is a bit different, but I don't use the refiner and rely on sharp models to begin with!

Thanks for considering it! ❤️

**Comment by mcmonkey4eva** [comment]
I don't think anything broke or changed related to SDXL - likely you're encountering whatever dev branch change caused #60

**Comment by oliverban** [comment]
When activating it, it doesn't work when used with XL on A111 1.6.0 but maybe it's something else? ;) Thanks for the response though!

**Comment by oliverban** [comment]
> 

I guess it is, but will try again!
