### ISSUE TITLE
NotImplementedError after updating A1111

### ISSUE THREAD

**Issue by phokphokphok** [mcmonkeyprojects/sd-dynamic-thresholding#64]
I'm getting this error after updating A1111 to the latest version. I think it's due to this extension since I'm able to generate when it's disabled:
```
File "/content/sdw/modules/sd_samplers_cfg_denoiser.py", line 63, in inner_model
        raise NotImplementedError()
```

**Comment by captainzero93** [comment]
if it does work, does it work with SDXL ?

**Comment by mcmonkey4eva** [comment]
@phokphokphok update the extension, this was fixed a couple weeks ago.
@captainzero93 yes it does - see #56 for notes on that
