### ISSUE TITLE
WEBUI 1.6 Cannot use refiner and dynamic threshold at the same time.

### ISSUE THREAD

**Issue by yamasoo** [mcmonkeyprojects/sd-dynamic-thresholding#69]
AttributeError: 'CompVisDenoiser' object has no attribute 'sampler_extra_args'

![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/73381291/b6c2fd5f-f799-4c96-968f-ff210127577c)

**Comment by mcmonkey4eva** [comment]
Love when auto webui updates reorganize random params without warnings and break things. Pushed a fix^
