### ISSUE TITLE
Love this but it doesn't seem to work with Loras.

### ISSUE THREAD

**Issue by michaelLochlann** [mcmonkeyprojects/sd-dynamic-thresholding#72]
hi guys, i've been using this for the past few days and it works great normally.

But if you add a Lora such as "Very Long Hair", it gets completely shredded if you leave it on say CFG 30.  Putting it back to CFG 7 looks great again.  

I don't know how this stuff works but maybe you guys can do something about it.  It's hard enough to get prompts to listen to you on CFG 30 lol

**Comment by michaelLochlann** [comment]
Example prompt
 girl, very_long_hair,  <lora:very_long_hair:0.4>
CFG 30 + your fix: the lora works but the whole picture looks shredded
CFG 7 + your fix: the lora works fine
CFG 30 + you fix +no lora: been using it for days with no issues.

**Comment by mcmonkey4eva** [comment]
some loras burn the model, and you have to compensate even harder - eg set the mimic cfg lower, or use the advanced settings (check examples in the wiki)
