### ISSUE TITLE
Mimic Scale and CFG Scale

### ISSUE THREAD

**Issue by ddoscv** [mcmonkeyprojects/sd-dynamic-thresholding#74]
Hi, I've been using this extension for a long time now and it's such an awesome thing to have, so thank you for making this and sharing it to everyone. But I had to reinstall my extensions and noticed the UI isn't the same as before. It used to have Mimic and CFG scale which was recommended to set to "3" if I remember correctly but now it is laid out differently. 

The UI looks like this now: 
https://puu.sh/JRyCg/a1a0124464.jpg
I have some questions:
1. Where should I set the mimic and cfg to "3"? Or do I not need to do that anymore with the latest version?
2. What does the "Separate Feature Channels" "Scaling Starting point" and "Variability Measure" do?
3. Is the default for "Scaling Starting point" = MEAN and "Variability Measure" = STD? I might have clicked these by accident without knowing.

**Comment by mcmonkey4eva** [comment]
`Where should I set the mimic and cfg to "3"?` i'm not sure where this came from? but the inputs are all the same, there's just new ones now.
Read through the wiki for usage hints https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/wiki

`What does the "Separate Feature Channels" "Scaling Starting point" and "Variability Measure" do?` https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/issues/73#issuecomment-1743880562

`Is the default for "Scaling Starting point" = MEAN and "Variability Measure" = STD? I might have clicked these by accident without knowing.` as far as auto webui goes any time you're in doubt on that, just close the tab and reopen, everything goes back to default (If you use DynThresh in StableSwarmUI it'll persist choices but it also tells you what defaults are and all)

**Comment by ddoscv** [comment]
Hi, thank you very much for the response, very helpful. And thanks for the extension again. No way I can use SD without this extension anymore :)

**Comment by mcmonkey4eva** [comment]
Oh, the minimums are disabled by default and only appear when you change the scheduler (because the default value of `constant` does not have a minimum), it appears it may have momentarily glitched for you?

**Comment by ddoscv** [comment]
Hello, I think I found the problem that causes it. The slider doesn't show even it's set to "Half Cosine Up" or anything else if I loaded [last used prompts/settings from the webui](https://puu.sh/JRGQX/f5151e285c.jpg). So I have to click on something else on the drop down arrow or click the "Half Cosine Up" again. But I'm not sure if mine is just buggy since I did upgrade to 1.6 but had to rollback later to previous versions so it may have contributed to that. So mine is probably just glitching because of these, but pretty minor issue and I can live with it.

**Comment by ddoscv** [comment]
Hi, I also just like to add that despite it's not showing the slider sometimes, it seems to have saved the value anyways just as seen in this screenshot when I checked the notepad for the generation info.
https://puu.sh/JRJ2a/d5b6ff0611.jpg

Sorry to bother you, And again, thanks for this extension :)
