### ISSUE TITLE
can this work with complex numbers?

### ISSUE THREAD

**Issue by gschian0** [mcmonkeyprojects/sd-dynamic-thresholding#8]
I did a fork and added tangent function just to test ...  I'm curious to use complex numbers processing ... maybe just tie in x and y for a single operation ?

**Comment by mcmonkey4eva** [comment]
I'm... not really sure what you mean, where/how complex numbers would be applicable?
I see your fork to add `tan` as a scale scheduler, and, uh, not sure the goal of that either? Shape of a tangent doesn't really make sense in this context, unless you know something I don't.

**Comment by gschian0** [comment]
I am going to add frequency controls to the scheduling as well...

[https://www.naturalspublishing.com/files/published/7px0r964d727hj.pdf](url)

[https://www.ventrella.com/mandelbrotgenetics/#:~:text=The%20Mandelbrot%20equation%20is%20z,input%20for%20the%20next%20iteration.](url)

![Mandelbrot Genetics and 110 more pages - Personal - Microsoft​ Edge 2_7_2023 2_15_02 PM](https://user-images.githubusercontent.com/54407820/217344268-84017deb-6ab1-410a-9b09-e44026f813c1.png)

**Comment by gschian0** [comment]
`https://www.jstor.org/stable/3211856?read-now=1#page_scan_tab_contents`

**Comment by mcmonkey4eva** [comment]
If you manage to get something useful and functional working, feel free to PR it.
