### ISSUE TITLE
When used with ComfyUI's smZNodes custom node produces noisy images.

### ISSUE THREAD

**Issue by toyxyz** [mcmonkeyprojects/sd-dynamic-thresholding#81]
I used smZNodes custom node in Comfyui to get the same result as A1111 webui. However, when I used it with dynamic-thresholding, it produced a noisy image unlike the webui.

smZNodes : https://github.com/shiimizu/ComfyUI_smZNodes#smznodes
ComfyUI workflow : [test.json](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/files/13197903/test.json)

![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/8006000/66d92aeb-c747-47bd-aa7d-21f121e6efda)
![workflow (28)](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/8006000/d026a2ef-39b5-404a-b423-40f7cef9633c)

**Comment by mcmonkey4eva** [comment]
Does this only happen with smZNodes -- by which I mean, if you replace those to the standard cliptextencode nodes, does it work normally?

**Comment by toyxyz** [comment]
> Does this only happen with smZNodes -- by which I mean, if you replace those to the standard cliptextencode nodes, does it work normally?

In my tests, the results are different from the webui even when using the standard cliptextencode. In webui, the lighting is generally smoother, but in ComfyUI it seems to be darker or noisier. Could this be due to an update to ComfyUI's sampler? 

![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/8006000/8c2be8ba-ce6d-41b0-8ed0-191e05b3bd68)

**Comment by mcmonkey4eva** [comment]
After some investigating, I've realized that ComfyUI actually processes sampling in a fundamentally different way than autowebui does (Auto uses the Denoised conditioning, Comfy uses the Predicted Noise).

So in effect right now the comfy node for dynthresh is operating in reverse of what it should be. (I... should have tested more carefully when I first published the comfy version. Eck.)

I'm at a bit of a loss for how to correct for that within ComfyUI, so I've reached out to comfy himself to ask for help on that.

**Comment by mcmonkey4eva** [comment]
Comfy updated the code to fix the core issue -- https://github.com/comfyanonymous/ComfyUI/commit/1777b54d0217e77a6a64b0a587b9b11a48e3bf02 so if you update Comfy and try again, it should work?

Let me know if anything's still different from expected results.

**Comment by toyxyz** [comment]
> Comfy updated the code to fix the core issue -- [comfyanonymous/ComfyUI@1777b54](https://github.com/comfyanonymous/ComfyUI/commit/1777b54d0217e77a6a64b0a587b9b11a48e3bf02) so if you update Comfy and try again, it should work?
> 
> Let me know if anything's still different from expected results.

Thank you, it's working now. 
![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/8006000/ed8c4f8a-683b-4fc3-9bc3-63d2a3d125a9)
