### ISSUE TITLE
Scheduled Value (in ComfyUI node) seems to do nothing? 

### ISSUE THREAD

**Issue by EricRollei** [mcmonkeyprojects/sd-dynamic-thresholding#84]
Thanks for making this node for Comfy.  Maybe more of a question than a bug...   It's super hard to find detailed info on what some of the features do so I've been doing XY testing.   In that testing, it appears that the sched_val  setting does not change anything.   Is it there just for organizational purposes ie to keep track of what the user intends to set CFG in the sampler? or was it there to do something? Or did it come from the A1111 port?

**Comment by mcmonkey4eva** [comment]
`[DT] Scheduler Value` if that's what you're referring to, is part of Dynamic Thresholding, which is documented in detail @ <https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/wiki>

If you view the parameter in the normal param list (under Advanced in this case), there's a `?` you can click for in-UI documentation
![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/4000772/e405699e-cf33-4efd-b2ac-898648adff24)

If you meant the Scheduler Type, that's a sub-parameter of Sampler. Auto WebUI combines Sampler+Scheduler into one (eg "DPM++ 2M Karras" is the sampler "DPM++ 2M" with the scheduler "Karras"). Sampler specifics are fairly minor and don't need to be fiddle with much.

**Comment by EricRollei** [comment]
Hey, I read the wiki first, didn't find any info on that setting but thank you for the quick reply.      Is it perhaps only use when you have Power Up selected?  Power-up needs a variable?  
![image](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/97568200/064e06f3-c9aa-4bd1-93a4-47a3698f45cd)

**Comment by mcmonkey4eva** [comment]
sched_val _is_ Scheduler Value, as explained in the screenshot above and also at <https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/wiki/Schedulers>
