### ISSUE TITLE
work with comfyui

### ISSUE THREAD

**Issue by Reginald-L** [mcmonkeyprojects/sd-dynamic-thresholding#91]
I try to use the dynamic node to fix cfg, but it seems not to work in my case, may I get any help?
<img width="617" alt="Snipaste_2024-01-22_15-45-18" src="https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/67569154/7a234e99-0ebb-4456-80ce-1c9506ffe499">

<img width="622" alt="Snipaste_2024-01-22_15-46-57" src="https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/assets/67569154/53a59c69-2fa3-4a5f-aad2-2d31ea92b89b">

**Comment by mcmonkey4eva** [comment]
LCM cannot handle such high CFGs, it needs 1-2 CFG. You might be able to get part of the way there by just setting Mimic Scale to 1 or 2
