### ISSUE TITLE
Nodes not showing up in ComfyUI

### ISSUE THREAD

**Issue by Kepler-16b** [mcmonkeyprojects/sd-dynamic-thresholding#92]
Installed with manager, comfyUI restarted but the nodes are not there. 
ComfyUI commit - [f2d43f](https://github.com/comfyanonymous/ComfyUI/commit/f2d432f9a754f2bacb85a70f7e2b817e6dba44f8)

**Comment by mcmonkey4eva** [comment]
Any error in the comfy console logs?

**Comment by alex20011104** [comment]
我同样遇到这个情况。I'm in the same situation.

**Comment by mcmonkey4eva** [comment]
need logs or details to diagnose anything

**Comment by alex20011104** [comment]
I previously set it up incorrectly. Thank you for your reply. My problem has been resolved
