### ISSUE TITLE
A Simple Request and\or Request for Guidance

### ISSUE THREAD

**Issue by ArmyOfPun1776** [mcmonkeyprojects/sd-dynamic-thresholding#95]
First off let me me teel you I love the extension.  

I am using a Preset extension called "Config Presets" (https://github.com/Zyin055/Config-Presets).  This extension allows me to add custom fields for 3rd party extensions like yours using `elem_id` for desired modules.  

I've had 0 issue adding all of the id(s) from your extension to the config save one. The checkbox to enable the extension doesn't have and `elem_id`.   

I don't know the first thing about adding such a thing to the code myself as far as setting the target.  

Could you maybe point me in the right direction as to how I'd go about doing this for the checkbox specifically?

Thanks in advance for any reply.

**Comment by mcmonkey4eva** [comment]
oh, yeah, that accidentally got deleted in a PR -- it's added back now

**Comment by ArmyOfPun1776** [comment]
Awesome! Thank you.
