### ISSUE TITLE
Conflict with 'prompt all in one' plugin

### ISSUE THREAD

**Issue by yincangshiwei** [mcmonkeyprojects/sd-dynamic-thresholding#96]
After installing the plugin, the "prompt all in one" plugin prompts connection failure.
After installing the plugin, the prompt all in one plugin prompts connection failure. I am using the latest version of prompt all in one.

**Comment by mcmonkey4eva** [comment]
Thaaat sounds like an error in the "prompt all in one" side rather than dynamic thresholding? DT has nothing to do with prompts / connections / etc.
